name: "Clean LFS Storage"
on:
  workflow_dispatch:

jobs:
  clean-lfs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          sudo apt-get update
          sudo apt-get install -y git-filter-repo

      - name: Check Initial LFS Storage
        run: |
          git lfs install
          echo "Initial LFS storage usage:"
          git lfs ls-files -l | awk '{total += $4} END {print total/1024/1024 " MB"}'

      - name: Clean LFS
        run: |
          # Configure git
          git config --global user.email "dygons14@gmail.com"
          git config --global user.name "sniezka"

          # Stash any unstaged changes
          git stash push --include-untracked || true

          # List all LFS files before cleaning
          echo "Current LFS files:"
          git lfs ls-files

          # Remove LFS tracking
          git lfs untrack "data/*_mainnet.json"
          git add .gitattributes
          git commit -m "Remove LFS tracking" || true

          # Remove old LFS objects
          git lfs prune
          git gc
          git lfs prune --force

          # Use git filter-repo to remove files from history
          git filter-repo --force --invert-paths --path "data/*_mainnet.json"

          # Force garbage collection
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

          # Re-apply stashed changes if any
          git stash pop || true

      - name: Reinitialize LFS
        run: |
          git lfs install
          git lfs track "data/*_mainnet.json"
          git add .gitattributes
          git commit -m "Reset LFS tracking" || echo "No changes to commit"

      - name: Force Push Changes
        run: |
          # Re-add the origin remote
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/Sniezka1927/git-lfs.git"

          # Push all changes forcefully
          git push origin master --force
          git push origin --force --all
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Check Final LFS Storage
        run: |
          echo "Final LFS storage usage:"
          git lfs ls-files -l | awk '{total += $4} END {print total/1024/1024 " MB"}'
