name: "Cleanup Git LFS Storage"
on:
  workflow_dispatch: # Manual trigger only for safety

jobs:
  cleanup-lfs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Clean working directory
        run: |
          # Reset any changes in the working directory
          git reset --hard HEAD
          git clean -fd

      - name: Remove LFS tracking and objects
        run: |
          # Show current LFS files
          echo "Currently tracked LFS files:"
          git lfs ls-files

          # Store LFS patterns before removing .gitattributes
          LFS_PATTERNS=$(git lfs track | grep -v "Listing tracked patterns" || echo "*.json")
          echo "LFS patterns: $LFS_PATTERNS"

          # Remove LFS tracking
          git lfs untrack "data/*_mainnet.json"

          # Migrate LFS objects to regular files
          git lfs migrate export --include="data/*_mainnet.json" --everything --yes

          # Remove .gitattributes
          rm -f .gitattributes

          # Clean up LFS cache and configs
          rm -rf .git/lfs
          git config --unset-all filter.lfs.required || true
          git config --unset-all filter.lfs.clean || true
          git config --unset-all filter.lfs.smudge || true
          git config --unset-all filter.lfs.process || true

          # Remove any remaining LFS configs from git config
          git config --local --unset-all filter.lfs.required || true
          git config --local --unset-all filter.lfs.clean || true
          git config --local --unset-all filter.lfs.smudge || true
          git config --local --unset-all filter.lfs.process || true

      - name: Stage and commit changes
        run: |
          # Stage all changes including untracked files
          git add -A .

          # Commit changes
          git commit -m "Remove Git LFS tracking and convert LFS objects to regular files" || echo "No changes to commit"

          # Force push to remove LFS history
          git push origin HEAD --force
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Verify cleanup
        run: |
          echo "Checking for any remaining LFS files:"
          git lfs ls-files || echo "No LFS files found - cleanup successful"

          echo "Checking for remaining LFS configurations:"
          git config --list | grep lfs || echo "No LFS configs found"
