name: "Cleanup Git LFS Storage"
on:
  workflow_dispatch: # Manual trigger only for safety

jobs:
  cleanup-lfs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Remove LFS tracking and objects
        run: |
          # Identify LFS tracked files
          echo "Currently tracked LFS files:"
          git lfs ls-files

          # Remove LFS tracking from .gitattributes
          rm -f .gitattributes

          # Uninstall LFS from repo
          git lfs uninstall

          # Remove all LFS pointers and replace with actual files
          git lfs migrate export --everything

          # Clean up LFS cache
          rm -rf .git/lfs

          # Remove any remaining LFS configs
          git config --unset-all filter.lfs.required
          git config --unset-all filter.lfs.clean
          git config --unset-all filter.lfs.smudge
          git config --unset-all filter.lfs.process

      - name: Commit changes
        run: |
          # Stage all changes
          git add -A

          # Create commit
          git commit -m "Remove Git LFS tracking and objects" || echo "No changes to commit"

          # Force push to remove LFS history
          git push origin HEAD --force
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Verify cleanup
        run: |
          echo "Checking for any remaining LFS files:"
          git lfs ls-files || echo "No LFS files found - cleanup successful"
