name: "Cleanup Git LFS Storage"
on:
  workflow_dispatch: # Manual trigger only for safety

jobs:
  cleanup-lfs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Clean working directory
        run: |
          # Reset any changes in the working directory
          git reset --hard HEAD

          # Clean untracked files
          git clean -fd

      - name: Remove LFS tracking and objects
        run: |
          # Show current LFS files
          echo "Currently tracked LFS files:"
          git lfs ls-files

          # Commit any pending changes to avoid dirty working directory
          git add -A
          git commit -m "Commit pending changes before LFS cleanup" || echo "No changes to commit"

          # Remove LFS tracking from .gitattributes
          rm -f .gitattributes

          # Uninstall LFS
          git lfs uninstall

          # Force migrate LFS objects to regular files
          git lfs migrate export --yes --everything

          # Clean up LFS cache and configs
          rm -rf .git/lfs
          git config --unset-all filter.lfs.required || true
          git config --unset-all filter.lfs.clean || true
          git config --unset-all filter.lfs.smudge || true
          git config --unset-all filter.lfs.process || true

      - name: Commit changes
        run: |
          # Stage all changes
          git add -A

          # Create commit
          git commit -m "Remove Git LFS tracking and objects" || echo "No changes to commit"

          # Force push to remove LFS history
          git push origin HEAD --force
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Verify cleanup
        run: |
          echo "Checking for any remaining LFS files:"
          git lfs ls-files || echo "No LFS files found - cleanup successful"
